map_frame: "map"
robot_frame: "robot_frame"
map_topic: "/octomap_binary"
goal_pose_sub_topic_name: "/goal_pose_sub_topic_name"
global_path_pub_topic_name: "/global_planner/path"
model_cube_size: "0.25"
bound_min: "-10"
bound_max: "10"
goal_frame: "goal_frame"